version: '2'

services:
  cuttingedge_db:
    image: mongo:3
    volumes:
      - $PWD/data:/var/lib/db
    ports:
      - "27017:27017"
  cuttingedge_app:
    build: .
    image: cuttingedge/app:latest
    depends_on:
      - cuttingedge_db
    links:
      - cuttingedge_db:cuttingedge_db
    ports:
      - "80:8080"
    restart: "on-failure"
#  cuttingedge_proxy:
#    image: nginx:1
#    depends_on:
#      - cuttingedge_app
#    links:
#      - cuttingedge_app:cuttingedge_app
#    ports:
#      - "80:80"